# Generated by Django 5.2.3 on 2025-07-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['creado_en'], 'verbose_name': 'Cursos', 'verbose_name_plural': 'Cursos'},
        ),
    ]
