# Generated by Django 5.2.3 on 2025-07-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_rename_curso_cursos_alter_cursos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='costo',
            field=models.FloatField(default=0.0, verbose_name='Costo del Curso'),
        ),
    ]
