# Generated by Django 5.2.3 on 2025-07-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_cursos_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Detalles de la Actividad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.cursos', verbose_name='Curso relacionado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
